# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache Repo
      # https://github.com/marketplace/actions/cache?version=v1.1.2
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers>" > ~/.m2/settings.xml
        echo "<server><id>github</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server>" >> ~/.m2/settings.xml
        echo "<server><id>github-alfresco-base</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server>" >> ~/.m2/settings.xml
        echo "<server><id>github-alfresco-test</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server>" >> ~/.m2/settings.xml
        echo "</servers></settings>" >> ~/.m2/settings.xml
        cat ~/.m2/settings.xml
        mvn -Dmaven.test.skip -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      env:
        # GITHUB_REPOSITORY: The owner and repository name. For example, octocat/Hello-World.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
        mvn -Dmaven.test.skip -B deploy -DaltDeploymentRepository="${REPO}" -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"
